//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWIClientReleaseTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ressources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ressources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWIClientReleaseTool.ressources", typeof(ressources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msvcp140.dll
        ///Qt5Charts.dll
        ///Qt5Core.dll
        ///Qt5Gui.dll
        ///Qt5Network.dll
        ///Qt5Widgets.dll
        ///SWInstaller.exe
        ///WizardClicker.json
        ///qjpeg.dll
        ///qwindows.dll
        ///client_init.json
        ///DotGobbler.png
        ///Gradient.png
        ///Presentation.md
        ///SWI_Logo.png
        ///SWI_Logo2.png
        ///ThankYouForPlaying.png
        ///AutoClicker.lib
        ///boost_date_time-vc141-mt-x64-1_70.dll
        ///brotlicommon.dll
        ///brotlidec.dll
        ///brotlienc.dll
        ///ClickerServer.exe
        ///cpprest_2_10.dll
        ///LIBEAY32.dll
        ///SSLEAY32.dll
        ///zlib1.dll
        ///qwindowsvistastyle.dll
        ///.
        /// </summary>
        public static string AuthorizeFiles {
            get {
                return ResourceManager.GetString("AuthorizeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] msvcp140 {
            get {
                object obj = ResourceManager.GetObject("msvcp140", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
